## Exercise.  1984 United States Congressional Voting Records

Now we are going to classify a more difficult dataset: The 1984 United States Congressional Voting Records.

 This data set includes votes for each of the U.S. House of Representatives Congressmen on 16 key votes
In origin they were nine different types of votes: 
     
* voted for, paired for, and announced for (these three simplified to yea or 'y'),
* voted against, paired against, and announced against (these three simplified to nay or 'n'), 
* voted present, voted present to avoid conflict of interest, and did not vote or otherwise make a position known 
     (these three simplified to an 'unknown' disposition)

The goal is to classify Congressmen as Republican or Democrat as a function of their voting profiles,
which is not immediate because in the US Congressmen have a large freedom of vote 
 (obviously linked to their party but also to their own feelings, interests and compromises with voters).
 
For the sake of the exercise, we will asume that it is more important to us to classify correctly the senators from the democrat party, as they are the ones currently ruling. 

Now we will folow the same structure than in the lab but with this dataset:

- [ ] Visualize your dataset. Does it have anything strange? Is it easy or difficult for our models? 
- [ ] Design a resampling protocol for your problem. ( E.g train-val-test, train-test with cross-val metrics...) 
- [ ] Design a pre-processing for your dataset and apply it to your partitions. 
- [ ] Chose the best metrics for your problem ( taking into account that it is more important to us to classify correctly the senators from the democrat party). 
- [ ] Train a LDA model.
- [ ] Train a QDA model.  
- [ ] Train a KNN model with cross-validation.  
- [ ] Train a Naive Bayes model, you should chose the probability distribution that adapts the best to your data. 
- [ ] Train a Logistic Regression model.
- [ ] Compare your models using the resampling protocol you chose. Do the results show strong differences?
- [ ] Compute the generalization performance of the best model.

In [2]:
import pandas as pd
from ucimlrepo import fetch_ucirepo

# Fetch dataset
house_votes = fetch_ucirepo(id=105)

# Extract features and labels
X = house_votes.data.features
y = house_votes.data.targets

# Convert to Pandas DataFrame (optional)
df = pd.concat([X, y], axis=1)

# Display first few rows
display(df.head())


print(df.shape)

df.describe()

,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa,Class
0,n,y,n,y,y,y,n,n,n,y,NaN,y,y,y,n,y,republican
1,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,NaN,republican
2,NaN,y,y,NaN,y,y,n,n,n,n,y,n,y,y,n,n,democrat
3,n,y,y,n,NaN,y,n,n,n,n,y,n,y,n,n,y,democrat
4,y,y,y,n,y,y,n,n,n,n,y,NaN,y,y,y,y,democrat

(435, 17)

,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa,Class
count,423,387,424,424,420,424,421,420,413,428,414,404,410,418,407,331,435
unique,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
top,n,y,y,n,y,y,y,y,y,y,n,n,y,y,n,y,democrat
freq,236,195,253,247,212,272,239,242,207,216,264,233,209,248,233,269,267